### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by nathf** [alexreardon/raf-stub#49]
Thanks for the lib @alexreardon 

When importing this module in TS webpack throws a wobbly using esnext modules:

```
ERROR in ./node_modules/raf-stub/src/index.js
Module parse failed: Unexpected token (5:5)
You may need an appropriate loader to handle this file type.
| import { defaultFrameDuration } from './constants';
| 
| type Stub = {|
|     add: (cb: Function) => number,
|     remove: (id: number) => void,
```

Is it possible to transition to flow comment types or if you have any other ideas? 

Happy to raise a PR for comment types

**Comment by alexreardon** [comment]
Your bundler is pulling in a file that uses flowtype. Either you build will need to be aware of flowtype, or it will need to pull in a different file. If you use the default export you should be fine:

```json
"main": "lib/index.js",
```
https://github.com/alexreardon/raf-stub/blob/master/package.json#L5

**Comment by nathf** [comment]
Thanks @alexreardon , i'll go with the latter :)

**Comment by Dobby89** [comment]
@alexreardon Any plans to create a types definition over at https://github.com/DefinitelyTyped/DefinitelyTyped? I'm getting the following warning in my editor.

![could not find declaration file for raf-stub](http://drive.google.com/uc?export=view&id=1MmqxHCHBIMX4-NDx6Q3fNT3fgVGCUwpM)
